export enum Role {
  ADMIN = 'admin',
  EXECUTIVE_MANAGER = 'EXECUTIVE_MANAGER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  SERVICE_HEAD = 'SERVICE_HEAD',
  UNIT_HEAD = 'UNIT_HEAD',
  EMPLOYEE = 'EMPLOYEE',
  RH = 'RH',
}
